graph LR
  Notfit
  Boxers
  Male
  Female

  MaleJunior["Male Junior"]
  MaleYouth["Male Youth"]
  MaleSenior["Male Senior"]
  
  Boxers --> Male
  Boxers -->|Not Fit| Notfit
  Boxers --> Female

  Male -->|YOB 2007| MaleSenior
  Male -->|YOB 2008,2009| MaleYouth
  Male -->|YOB 2010,2011,2012,2013| MaleJunior

  Female -->| |FemaleSparMatch1
  Female -->| |FemaleSparMatch2
  Female -->| |FemaleSparMatch3

  MaleJunior -->| |MaleJuniorWeightClasses
  MaleYouth -->| |MaleYouthWeightClasses
  MaleSenior -->| |MaleSeniorWeightClasses
  

    
  MaleJuniorWeightClasses -->| |MaleJuniorEXC1
  MaleJuniorWeightClasses -->| |MaleJuniorEXC2
  
  MaleYouthWeightClasses -->| |MaleYouthEXC1
  MaleYouthWeightClasses -->| |MaleYouthEXC2
  
  MaleSeniorWeightClasses -->| |MaleSeniorEXC1
  MaleSeniorWeightClasses -->| |MaleSeniorEXC2 
  
  MaleJuniorEXC1 -->| |MaleJuniorSparMatch1
  MaleJuniorEXC1 -->| |MaleJuniorSparMatch2
  MaleJuniorEXC2 -->| |MaleJuniorSparMatch3
  MaleJuniorEXC2 -->| |MaleJuniorSparMatch4
  
  MaleYouthEXC1 -->| |MaleYouthSparMatch1
  MaleYouthEXC1 -->| |MaleYouthSparMatch2
  MaleYouthEXC2 -->| |MaleYouthSparMatch3
  MaleYouthEXC2 -->| |MaleYouthSparMatch4

  MaleSeniorEXC1 -->| |MaleSeniorSparMatch1
  MaleSeniorEXC1 -->| |MaleSeniorSparMatch2
  MaleSeniorEXC2 -->| |MaleSeniorSparMatch3
  MaleSeniorEXC2 -->| |MaleSeniorSparMatch4
  

